# -*- coding: utf-8 -*-
"""prashu.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x04R2Ptg1PfiahnSShAuoRTAeuKnt3i7
"""

import numpy as np
x=([1,2,3,4])
print(x)

import numpy as np
x=np.array([1,2,3,4])
print(x)
print(type(x))

import numpy as np
x=np.array([1,2,3,'n',4])
print(x)
print(type(x))

import numpy as np
y=np.linspace(start=1,stop=5)
print (y)

import numpy as np
x=np.arange(start=1,stop=20,step=2)
print(x)

import numpy as np
x=np.ones((3,3))
print(x)

import numpy as np
x=np.zeros((3,3))
print(x)

import numpy as np
x=np.random.rand(2,5)
print(x)

import numpy as np
x=10*np.random.rand(10)
x=x.astype(int)
print(x)