# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/164r6J_788I8gBghw_TZbXJaZfu29wFvT

# **DESCRIPTION**
**OUR DATA IS ABOUT GOOGLE PLAYSTORE APPS**

 **APPS**: app is a computer program or software application designed to run on a mobile device such as a phone, tablet, or watch.  
 
 **CATEGORY**:a class or division of people or things regarded as having particular shared characteristics.

 **RATING**:A rating is an evaluation or assessment of something, in terms of quality, quantity, or some combination of both.
 
 **REVIEWS**:A critical appraisal of a book,play,film,etc.published in a newspaper or magazine.

 **SITE**:a set of related web pages, typically with a common domain name and hosted on at least one web server.

 **INSTALLS**: to put in place or connect for service or use.

**TYPE**:a category of people or things having common characteristics.

**PRIZE**:something of great value that is worth.

**CONTENT**:the information and experiences that are directed toward an end-user or audience.

**GENRES**:a style or category of art, music, or literature.

**LAST UPDATED**:the last modification of an app.

**CURRENT VERSION**:the current andriod version in mobile.

**ANDROID VERSION**: Android is a mobile operating system developed by Google. It is used by several smartphones and tablets.

### **Reading data**
"""

#import pandas
import pandas as pd

"""### **Reading data**"""

apps=pd.read_csv('/content/googleplaystore.csv')
print(apps)

